#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Project_2.py
#  
#  Copyright 2018 penjo <penjo@vik3rn35>
#  
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
#  
#  



def main():
	
	fib = []
	for i in range(4000000)
		
	return 0

if __name__ == '__main__':
	main()

